cmake_minimum_required(VERSION 3.11)

# project information
project(simpleAscend)
set(PROJECT_INCLUDE ${PROJECT_SOURCE_DIR}/include)
set(PROJECT_LIBS)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "-D__STDC_CONSTANT_MACROS")
    
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)  
add_definitions(-Dgoogle=mindxsdk_private)      
add_compile_options(-std=c++17 -fPIC -fstack-protector-all -Wall)
    
set(CMAKE_CXX_FLAGS_DEBUG "-g")                           
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-z,relro,-z,now,-z,noexecstack -s -pie")
set(CMAKE_SKIP_RPATH TRUE)
    
find_package(Threads REQUIRED)
    
# Specify target generation path
set(CMAKE_CXX_FLAGS_DEBUG "-fPIC -O0 -g -Wall")
set(CMAKE_CXX_FLAGS_RELEASE "-fPIC -O2 -Wall")
    
set(CMAKE_PREFIX_PATH "/usr/local/lib64" ${CMAKE_PREFIX_PATH})
set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
set(MX_SDK_HOME $ENV{MX_SDK_HOME})      
set(ASCEND_HOME_PATH $ENV{ASCEND_HOME_PATH})
message("Ascend home: ${ASCEND_HOME_PATH}/${ARCH_PATTERN}")
    
if (NOT DEFINED ENV{MX_SDK_HOME})      
    string(REGEX REPLACE "(.*)/(.*)/(.*)/(.*)" "\\1" MX_SDK_HOME  ${CMAKE_CURRENT_SOURCE_DIR})
    message(STATUS "set default MX_SDK_HOME: ${MX_SDK_HOME}")
else ()
    message(STATUS "env MX_SDK_HOME: ${MX_SDK_HOME}")
endif()

list(APPEND PROJECT_INCLUDE "${MX_SDK_HOME}/include/")
list(APPEND PROJECT_INCLUDE "${MX_SDK_HOME}/opensource/include/")
list(APPEND PROJECT_INCLUDE "${MX_SDK_HOME}/opensource/include/opencv4/")
list(APPEND PROJECT_INCLUDE "$ENV{INSTALL_DIR}/runtime/include/")
list(APPEND PROJECT_INCLUDE "${ASCEND_HOME_PATH}/include")
list(APPEND PROJECT_INCLUDE "${ASCEND_HOME_PATH}/runtime/include")
    
set(ACL_LIB_PATH "${MX_SDK_HOME}/lib/")
list(APPEND ACL_LIB_PATH "${MX_SDK_HOME}/lib/modelpostprocessors/")
list(APPEND ACL_LIB_PATH "${MX_SDK_HOME}/opensource/lib/")
list(APPEND ACL_LIB_PATH "${MX_SDK_HOME}/opensource/lib64/")
list(APPEND ACL_LIB_PATH "${ASCEND_HOME_PATH}/atc/lib64")
list(APPEND ACL_LIB_PATH "/usr/lib64/")
    
#find FFmpeg include and library file
message("====== FIND FFMPEG LIBRARY AND INCLUDE ======")
find_path(FFMPEG_INCLUDE_DIR libavcodec/avcodec.h REQUIRED)
list(APPEND PROJECT_INCLUDE ${FFMPEG_INCLUDE_DIR})
find_library(AVCODEC_LIBRARY avcodec REQUIRED)
list(APPEND PROJECT_LIBS ${AVCODEC_LIBRARY})
find_library(AVFORMAT_LIBRARY avformat)
list(APPEND PROJECT_LIBS ${AVFORMAT_LIBRARY})
find_library(AVUTIL_LIBRARY avutil)
list(APPEND PROJECT_LIBS ${AVUTIL_LIBRARY})
find_library(AVDEVICE_LIBRARY avdevice)
list(APPEND PROJECT_LIBS ${AVDEVICE_LIBRARY})
find_library(AVFILTER_LIBRARY avfilter)
list(APPEND PROJECT_LIBS ${AVFILTER_LIBRARY})
find_library(SWRESAMPLE_LIBRARY swresample)
list(APPEND PROJECT_LIBS ${SWRESAMPLE_LIBRARY})
find_library(SWSCALE_LIBRARY swscale)
list(APPEND PROJECT_LIBS ${SWSCALE_LIBRARY})
message(STATUS "ffmpeg include:${FFMPEG_INCLUDE_DIR}")
message(STATUS "avcodec lib:${AVCODEC_LIBRARY}")
message(STATUS "avformat lib:${AVFORMAT_LIBRARY}")
message(STATUS "avutil lib:${AVUTIL_LIBRARY}")
message(STATUS "avdevice lib:${AVDEVICE_LIBRARY}")
message(STATUS "avfilter lib:${AVFILTER_LIBRARY}")
message(STATUS "swresample lib:${SWRESAMPLE_LIBRARY}")
message(STATUS "swscale lib:${SWSCALE_LIBRARY}")

#find Ascend include and library file
message("====== FIND ACL LIBRARY AND INCLUDE ======")
find_library(CL_LIB ascendcl PATHS ${ACL_LIB_PATH} REQUIRED)
list(APPEND PROJECT_LIBS ${CL_LIB})
find_library(DVPP_LIB acl_dvpp PATHS ${ACL_LIB_PATH} REQUIRED)
list(APPEND PROJECT_LIBS ${DVPP_LIB})
find_library(CBLAS_LIB acl_cblas PATHS ${ACL_LIB_PATH} REQUIRED)
list(APPEND PROJECT_LIBS ${CBLAS_LIB})
message("ACL_INCLUDE_DIR->${ACL_INCLUDE_DIR}")
message("CL_LIB->${CL_LIB}")
message("DVPP_LIB->${DVPP_LIB}")
message("CBLAS_LIB->${CBLAS_LIB}")
    
#find mxVision include and library file
message("====== FIND MINDX LIBRARY AND INCLUDE ======")
find_library(BASE_LIB mxbase PATHS ${ACL_LIB_PATH} REQUIRED)
list(APPEND PROJECT_LIBS ${BASE_LIB})
#find_library(PLUGIN_LIB plugintoolkit REQUIRED)
#list(APPEND PROJECT_LIBS ${PLUGIN_LIB})
#find_library(DATA_LIB mxpidatatype REQUIRED)
#list(APPEND PROJECT_LIBS ${DATA_LIB})
#find_library(STREAM_LIB streammanager REQUIRED)
#list(APPEND PROJECT_LIBS ${STREAM_LIB})
message("BASE_LIB->${BASE_LIB}")
#message("PLUGIN_LIB->${PLUGIN_LIB}")
#message("DATA_LIB->${DATA_LIB}")
#message("STREAM_LIB->${STREAM_LIB}")
    
#use opencv from mxVision
message("====== FIND OPENCV LIBRARY AND INCLUDE ======")
find_library(openCV_LIB opencv_world PATHS ${ACL_LIB_PATH} REQUIRED)
list(APPEND PROJECT_LIBS ${openCV_LIB})
message(STATUS "opencv include:${MX_SDK_HOME}/opensource/include/opencv4/")
message(STATUS "opencv lib:${openCV_LIB}")
    
message(" ====== FIND FREETYPE LIBRARY AND INCLUDE ======")
set(FREETYPE_DIR "/usr/include/freetype2")
find_library(FREETYPE_LIB freetype  REQUIRED)
list(APPEND PROJECT_INCLUDE ${FREETYPE_DIR})
list(APPEND PROJECT_LIBS ${FREETYPE_LIB})
message("FREETYPE_DIR->${FREETYPE_DIR}")
message("FREETYPE_LIB->${FREETYPE_LIB}")

message("CMAKE_PREFIX_PATH:" ${CMAKE_PREFIX_PATH})

include(${PROJECT_SOURCE_DIR}/include/acle/aclelink.cmake)
message("acle cpp: ${ACLE}")

add_subdirectory(samples/mindX)
add_subdirectory(samples/decandenc)